// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/storage/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6060443518060866028),
    name: 'ConversationEntity',
    lastPropertyId: const obx_int.IdUid(27, 5205524731612525260),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7250988890405982940),
        name: 'internalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6585352959757183870),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 4841541219215160349),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4528360812098110067),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6318468918758166025),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3060834012974707866),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 617250549526069739),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5786554614037038633),
        name: 'personaId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2861907472509737489),
        name: 'serverId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7707788543167527562),
        name: 'modelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6820164520934907732),
        name: 'messageCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3808591552035911328),
        name: 'lastMessagePreview',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 768672924450595967),
        name: 'systemPrompt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2024052842140577753),
        name: 'temperature',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4666617501498182545),
        name: 'topP',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6140239983637101227),
        name: 'maxTokens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 9154328066006661329),
        name: 'contextLength',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8783340423572117942),
        name: 'mcpEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2260684969168742247),
        name: 'smartRepliesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 2437473986237603139),
        name: 'smartRepliesLastMessageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 6746128880040296628),
        name: 'folderId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 4372897463643655414),
        name: 'isTemporary',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 2980396196878246454),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 3122805731877931734),
        name: 'characterCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 2324488738774851555),
        name: 'totalTokenCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 587693285257817302),
        name: 'forkOfMessageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 6295946776019084010),
        name: 'forkSpan',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 5205524731612525260),
        name: 'isFork',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'messages',
        srcEntity: 'MessageEntity',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 196881068437544233),
    name: 'MessageEntity',
    lastPropertyId: const obx_int.IdUid(29, 6028398201373029019),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3923220810652427930),
        name: 'internalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4538486775689812159),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 2170902273804247015),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2455937359218896797),
        name: 'conversationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 169510492024268969),
        relationField: 'conversation',
        relationTarget: 'ConversationEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9041846205772997953),
        name: 'conversationUid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 7620462177544383533),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3967309868246732396),
        name: 'roleIndex',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5292209498807417151),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4728980799803110489),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4723736841925529304),
        name: 'statusIndex',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5749988360982169067),
        name: 'modelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5208151897806410090),
        name: 'tokenCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5046757142081916519),
        name: 'errorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3014900088652314818),
        name: 'attachmentPathsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 754466339638382368),
        name: 'generationTimeMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6735567839050317594),
        name: 'reasoningContent',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2001265758949765605),
        name: 'toolCallsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6649517364442324198),
        name: 'toolCallId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6197342254666211356),
        name: 'isProcessing',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3862782083473953676),
        name: 'toolSessionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5573835801528383007),
        name: 'toolEventsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 1744774964291030898),
        name: 'variantGroupId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6711322182948396736),
        name: 'variantIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 5971161269391176967),
        name: 'threadOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 245069546630142341),
        name: 'isActiveVariant',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 5960797950716320436),
        name: 'parentMessageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 1552629421552033386),
        name: 'inputTokenCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 1965067209419994290),
        name: 'tokensPerSecond',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 7785830711210478899),
        name: 'ttftMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 8162956617579414275),
        name: 'stopReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 6028398201373029019),
        name: 'contentTokenCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2653818534060300073),
    name: 'PersonaEntity',
    lastPropertyId: const obx_int.IdUid(11, 6109868781061218611),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5387772201885529069),
        name: 'internalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 943547030981649537),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 271490381912735587),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5296359738005988766),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1099248784524684443),
        name: 'emoji',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5744781536100424228),
        name: 'systemPrompt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7306493291640402510),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3478346354108827230),
        name: 'isBuiltIn',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2536114129168373905),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2004523499979292665),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4803561724777818572),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6109868781061218611),
        name: 'preferredParamsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6971506781199819057),
    name: 'ServerEntity',
    lastPropertyId: const obx_int.IdUid(15, 6058370228992885505),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1193214592990508905),
        name: 'internalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1949522104474427292),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 4529386251594949074),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5435197030913688688),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5859746794128897561),
        name: 'typeIndex',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7884292605074234260),
        name: 'host',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2516802883134110310),
        name: 'port',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9034988768868935282),
        name: 'apiKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7825400106697971993),
        name: 'isDefault',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6761441426018420644),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9150237084363813165),
        name: 'lastConnectedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7342462043799432941),
        name: 'statusIndex',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4662365603702428254),
        name: 'iconName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6207430374144016939),
        name: 'pathPrefix',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5253774322138008698),
        name: 'availableRamGb',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6058370228992885505),
        name: 'availableVramGb',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8961477194169140955),
    name: 'ConversationFolderEntity',
    lastPropertyId: const obx_int.IdUid(5, 3017762750413225828),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6352437205361204397),
        name: 'internalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2340734036954615718),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 2357039312556022508),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3556260745512005959),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4019578934915258468),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3017762750413225828),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 152573122645768072),
    name: 'SavedMessageEntity',
    lastPropertyId: const obx_int.IdUid(11, 8907657125307211651),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5595034332359148209),
        name: 'internalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5096668802007679304),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 22783346841342476),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1050610104311264456),
        name: 'sourceMessageId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 1110570128952634448),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7798325361628325620),
        name: 'conversationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 8583926456518887322),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3050316078893132430),
        name: 'conversationTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7383260001962467499),
        name: 'roleIndex',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7504405387353170036),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4458386748227842718),
        name: 'modelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6741841406448273760),
        name: 'folderId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 431621328894537301),
        name: 'savedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8907657125307211651),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 3071607342535269584),
    name: 'SavedMessageFolderEntity',
    lastPropertyId: const obx_int.IdUid(5, 3331891664317498140),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7591361223634591419),
        name: 'internalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2427537233466774281),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(11, 4226689279810093888),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2751147963490618792),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3384073655383318255),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3331891664317498140),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 7895365751563937927),
    name: 'ForkAnchorEntity',
    lastPropertyId: const obx_int.IdUid(7, 7373507485623998526),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7132218893247571166),
        name: 'internalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7219532410895169266),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 8691070347134042097),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6419925018061405343),
        name: 'mainConversationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 8885298831567115071),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6165095474518001508),
        name: 'anchorMessageId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 3277257828143291386),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 324397342874350634),
        name: 'selectedText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 570210534330261134),
        name: 'forkConversationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(15, 7170761428673485654),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7373507485623998526),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 7895365751563937927),
    lastIndexId: const obx_int.IdUid(15, 7170761428673485654),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ConversationEntity: obx_int.EntityDefinition<ConversationEntity>(
      model: _entities[0],
      toOneRelations: (ConversationEntity object) => [],
      toManyRelations: (ConversationEntity object) => {
        obx_int.RelInfo<MessageEntity>.toOneBacklink(
          3,
          object.internalId,
          (MessageEntity srcObject) => srcObject.conversation,
        ): object.messages,
      },
      getId: (ConversationEntity object) => object.internalId,
      setId: (ConversationEntity object, int id) {
        object.internalId = id;
      },
      objectToFB: (ConversationEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final titleOffset = fbb.writeString(object.title);
        final personaIdOffset = object.personaId == null
            ? null
            : fbb.writeString(object.personaId!);
        final serverIdOffset = object.serverId == null
            ? null
            : fbb.writeString(object.serverId!);
        final modelIdOffset = object.modelId == null
            ? null
            : fbb.writeString(object.modelId!);
        final lastMessagePreviewOffset = object.lastMessagePreview == null
            ? null
            : fbb.writeString(object.lastMessagePreview!);
        final systemPromptOffset = object.systemPrompt == null
            ? null
            : fbb.writeString(object.systemPrompt!);
        final smartRepliesJsonOffset = object.smartRepliesJson == null
            ? null
            : fbb.writeString(object.smartRepliesJson!);
        final smartRepliesLastMessageIdOffset =
            object.smartRepliesLastMessageId == null
            ? null
            : fbb.writeString(object.smartRepliesLastMessageId!);
        final folderIdOffset = object.folderId == null
            ? null
            : fbb.writeString(object.folderId!);
        final forkOfMessageIdOffset = object.forkOfMessageId == null
            ? null
            : fbb.writeString(object.forkOfMessageId!);
        final forkSpanOffset = object.forkSpan == null
            ? null
            : fbb.writeString(object.forkSpan!);
        fbb.startTable(28);
        fbb.addInt64(0, object.internalId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(5, object.isPinned);
        fbb.addOffset(6, personaIdOffset);
        fbb.addOffset(7, serverIdOffset);
        fbb.addOffset(8, modelIdOffset);
        fbb.addInt64(9, object.messageCount);
        fbb.addOffset(10, lastMessagePreviewOffset);
        fbb.addOffset(11, systemPromptOffset);
        fbb.addFloat64(12, object.temperature);
        fbb.addFloat64(13, object.topP);
        fbb.addInt64(14, object.maxTokens);
        fbb.addInt64(15, object.contextLength);
        fbb.addBool(16, object.mcpEnabled);
        fbb.addOffset(17, smartRepliesJsonOffset);
        fbb.addOffset(18, smartRepliesLastMessageIdOffset);
        fbb.addOffset(19, folderIdOffset);
        fbb.addBool(20, object.isTemporary);
        fbb.addBool(21, object.isArchived);
        fbb.addInt64(22, object.characterCount);
        fbb.addInt64(23, object.totalTokenCount);
        fbb.addOffset(24, forkOfMessageIdOffset);
        fbb.addOffset(25, forkSpanOffset);
        fbb.addBool(26, object.isFork);
        fbb.finish(fbb.endTable());
        return object.internalId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final internalIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final personaIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final serverIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final modelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final messageCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final lastMessagePreviewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final systemPromptParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final temperatureParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final topPParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final maxTokensParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final contextLengthParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final mcpEnabledParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final smartRepliesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final smartRepliesLastMessageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final folderIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final isTemporaryParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          44,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          46,
          false,
        );
        final characterCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          48,
          0,
        );
        final totalTokenCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          50,
        );
        final forkOfMessageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final forkSpanParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 54);
        final isForkParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          56,
          false,
        );
        final object = ConversationEntity(
          internalId: internalIdParam,
          id: idParam,
          title: titleParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isPinned: isPinnedParam,
          personaId: personaIdParam,
          serverId: serverIdParam,
          modelId: modelIdParam,
          messageCount: messageCountParam,
          lastMessagePreview: lastMessagePreviewParam,
          systemPrompt: systemPromptParam,
          temperature: temperatureParam,
          topP: topPParam,
          maxTokens: maxTokensParam,
          contextLength: contextLengthParam,
          mcpEnabled: mcpEnabledParam,
          smartRepliesJson: smartRepliesJsonParam,
          smartRepliesLastMessageId: smartRepliesLastMessageIdParam,
          folderId: folderIdParam,
          isTemporary: isTemporaryParam,
          isArchived: isArchivedParam,
          characterCount: characterCountParam,
          totalTokenCount: totalTokenCountParam,
          forkOfMessageId: forkOfMessageIdParam,
          forkSpan: forkSpanParam,
          isFork: isForkParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<ConversationEntity>(
          object.messages,
          store,
          obx_int.RelInfo<MessageEntity>.toOneBacklink(
            3,
            object.internalId,
            (MessageEntity srcObject) => srcObject.conversation,
          ),
        );
        return object;
      },
    ),
    MessageEntity: obx_int.EntityDefinition<MessageEntity>(
      model: _entities[1],
      toOneRelations: (MessageEntity object) => [object.conversation],
      toManyRelations: (MessageEntity object) => {},
      getId: (MessageEntity object) => object.internalId,
      setId: (MessageEntity object, int id) {
        object.internalId = id;
      },
      objectToFB: (MessageEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final conversationUidOffset = fbb.writeString(object.conversationUid);
        final contentOffset = fbb.writeString(object.content);
        final modelIdOffset = object.modelId == null
            ? null
            : fbb.writeString(object.modelId!);
        final errorMessageOffset = object.errorMessage == null
            ? null
            : fbb.writeString(object.errorMessage!);
        final attachmentPathsJsonOffset = object.attachmentPathsJson == null
            ? null
            : fbb.writeString(object.attachmentPathsJson!);
        final reasoningContentOffset = object.reasoningContent == null
            ? null
            : fbb.writeString(object.reasoningContent!);
        final toolCallsJsonOffset = object.toolCallsJson == null
            ? null
            : fbb.writeString(object.toolCallsJson!);
        final toolCallIdOffset = object.toolCallId == null
            ? null
            : fbb.writeString(object.toolCallId!);
        final toolSessionIdOffset = object.toolSessionId == null
            ? null
            : fbb.writeString(object.toolSessionId!);
        final toolEventsJsonOffset = object.toolEventsJson == null
            ? null
            : fbb.writeString(object.toolEventsJson!);
        final variantGroupIdOffset = object.variantGroupId == null
            ? null
            : fbb.writeString(object.variantGroupId!);
        final parentMessageIdOffset = object.parentMessageId == null
            ? null
            : fbb.writeString(object.parentMessageId!);
        final stopReasonOffset = object.stopReason == null
            ? null
            : fbb.writeString(object.stopReason!);
        fbb.startTable(30);
        fbb.addInt64(0, object.internalId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.conversation.targetId);
        fbb.addOffset(3, conversationUidOffset);
        fbb.addInt32(4, object.roleIndex);
        fbb.addOffset(5, contentOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt32(7, object.statusIndex);
        fbb.addOffset(8, modelIdOffset);
        fbb.addInt64(9, object.tokenCount);
        fbb.addOffset(10, errorMessageOffset);
        fbb.addOffset(11, attachmentPathsJsonOffset);
        fbb.addInt64(12, object.generationTimeMs);
        fbb.addOffset(13, reasoningContentOffset);
        fbb.addOffset(14, toolCallsJsonOffset);
        fbb.addOffset(15, toolCallIdOffset);
        fbb.addBool(16, object.isProcessing);
        fbb.addOffset(17, toolSessionIdOffset);
        fbb.addOffset(18, toolEventsJsonOffset);
        fbb.addOffset(19, variantGroupIdOffset);
        fbb.addInt64(20, object.variantIndex);
        fbb.addInt64(21, object.threadOrder);
        fbb.addBool(22, object.isActiveVariant);
        fbb.addOffset(23, parentMessageIdOffset);
        fbb.addInt64(24, object.inputTokenCount);
        fbb.addFloat64(25, object.tokensPerSecond);
        fbb.addInt64(26, object.ttftMs);
        fbb.addOffset(27, stopReasonOffset);
        fbb.addInt64(28, object.contentTokenCount);
        fbb.finish(fbb.endTable());
        return object.internalId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final internalIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final conversationUidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final roleIndexParam = const fb.Int32Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final statusIndexParam = const fb.Int32Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final modelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final tokenCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final inputTokenCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          52,
        );
        final tokensPerSecondParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          54,
        );
        final ttftMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          56,
        );
        final stopReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 58);
        final errorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final attachmentPathsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final generationTimeMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final reasoningContentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final toolCallsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final toolCallIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final isProcessingParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          36,
          false,
        );
        final toolSessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final toolEventsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final variantGroupIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final variantIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final threadOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          46,
          0,
        );
        final isActiveVariantParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          48,
          false,
        );
        final parentMessageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final contentTokenCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          60,
        );
        final object = MessageEntity(
          internalId: internalIdParam,
          id: idParam,
          conversationUid: conversationUidParam,
          roleIndex: roleIndexParam,
          content: contentParam,
          createdAt: createdAtParam,
          statusIndex: statusIndexParam,
          modelId: modelIdParam,
          tokenCount: tokenCountParam,
          inputTokenCount: inputTokenCountParam,
          tokensPerSecond: tokensPerSecondParam,
          ttftMs: ttftMsParam,
          stopReason: stopReasonParam,
          errorMessage: errorMessageParam,
          attachmentPathsJson: attachmentPathsJsonParam,
          generationTimeMs: generationTimeMsParam,
          reasoningContent: reasoningContentParam,
          toolCallsJson: toolCallsJsonParam,
          toolCallId: toolCallIdParam,
          isProcessing: isProcessingParam,
          toolSessionId: toolSessionIdParam,
          toolEventsJson: toolEventsJsonParam,
          variantGroupId: variantGroupIdParam,
          variantIndex: variantIndexParam,
          threadOrder: threadOrderParam,
          isActiveVariant: isActiveVariantParam,
          parentMessageId: parentMessageIdParam,
          contentTokenCount: contentTokenCountParam,
        );
        object.conversation.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.conversation.attach(store);
        return object;
      },
    ),
    PersonaEntity: obx_int.EntityDefinition<PersonaEntity>(
      model: _entities[2],
      toOneRelations: (PersonaEntity object) => [],
      toManyRelations: (PersonaEntity object) => {},
      getId: (PersonaEntity object) => object.internalId,
      setId: (PersonaEntity object, int id) {
        object.internalId = id;
      },
      objectToFB: (PersonaEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final emojiOffset = fbb.writeString(object.emoji);
        final systemPromptOffset = fbb.writeString(object.systemPrompt);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final categoryOffset = object.category == null
            ? null
            : fbb.writeString(object.category!);
        final preferredParamsJsonOffset = object.preferredParamsJson == null
            ? null
            : fbb.writeString(object.preferredParamsJson!);
        fbb.startTable(12);
        fbb.addInt64(0, object.internalId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, emojiOffset);
        fbb.addOffset(4, systemPromptOffset);
        fbb.addOffset(5, descriptionOffset);
        fbb.addBool(6, object.isBuiltIn);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(9, categoryOffset);
        fbb.addOffset(10, preferredParamsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.internalId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final internalIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final emojiParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final systemPromptParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final isBuiltInParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final preferredParamsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final object = PersonaEntity(
          internalId: internalIdParam,
          id: idParam,
          name: nameParam,
          emoji: emojiParam,
          systemPrompt: systemPromptParam,
          description: descriptionParam,
          isBuiltIn: isBuiltInParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          category: categoryParam,
          preferredParamsJson: preferredParamsJsonParam,
        );

        return object;
      },
    ),
    ServerEntity: obx_int.EntityDefinition<ServerEntity>(
      model: _entities[3],
      toOneRelations: (ServerEntity object) => [],
      toManyRelations: (ServerEntity object) => {},
      getId: (ServerEntity object) => object.internalId,
      setId: (ServerEntity object, int id) {
        object.internalId = id;
      },
      objectToFB: (ServerEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final hostOffset = fbb.writeString(object.host);
        final apiKeyOffset = object.apiKey == null
            ? null
            : fbb.writeString(object.apiKey!);
        final iconNameOffset = object.iconName == null
            ? null
            : fbb.writeString(object.iconName!);
        final pathPrefixOffset = object.pathPrefix == null
            ? null
            : fbb.writeString(object.pathPrefix!);
        fbb.startTable(16);
        fbb.addInt64(0, object.internalId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt32(3, object.typeIndex);
        fbb.addOffset(4, hostOffset);
        fbb.addInt64(5, object.port);
        fbb.addOffset(6, apiKeyOffset);
        fbb.addBool(7, object.isDefault);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.lastConnectedAt.millisecondsSinceEpoch);
        fbb.addInt32(10, object.statusIndex);
        fbb.addOffset(11, iconNameOffset);
        fbb.addOffset(12, pathPrefixOffset);
        fbb.addInt64(13, object.availableRamGb);
        fbb.addInt64(14, object.availableVramGb);
        fbb.finish(fbb.endTable());
        return object.internalId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final internalIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeIndexParam = const fb.Int32Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final hostParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final portParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final apiKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final isDefaultParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final lastConnectedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final statusIndexParam = const fb.Int32Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final iconNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final pathPrefixParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final availableRamGbParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final availableVramGbParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final object = ServerEntity(
          internalId: internalIdParam,
          id: idParam,
          name: nameParam,
          typeIndex: typeIndexParam,
          host: hostParam,
          port: portParam,
          apiKey: apiKeyParam,
          isDefault: isDefaultParam,
          createdAt: createdAtParam,
          lastConnectedAt: lastConnectedAtParam,
          statusIndex: statusIndexParam,
          iconName: iconNameParam,
          pathPrefix: pathPrefixParam,
          availableRamGb: availableRamGbParam,
          availableVramGb: availableVramGbParam,
        );

        return object;
      },
    ),
    ConversationFolderEntity:
        obx_int.EntityDefinition<ConversationFolderEntity>(
          model: _entities[4],
          toOneRelations: (ConversationFolderEntity object) => [],
          toManyRelations: (ConversationFolderEntity object) => {},
          getId: (ConversationFolderEntity object) => object.internalId,
          setId: (ConversationFolderEntity object, int id) {
            object.internalId = id;
          },
          objectToFB: (ConversationFolderEntity object, fb.Builder fbb) {
            final idOffset = fbb.writeString(object.id);
            final nameOffset = fbb.writeString(object.name);
            fbb.startTable(6);
            fbb.addInt64(0, object.internalId);
            fbb.addOffset(1, idOffset);
            fbb.addOffset(2, nameOffset);
            fbb.addInt64(3, object.sortOrder);
            fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
            fbb.finish(fbb.endTable());
            return object.internalId;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final internalIdParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final idParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final nameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final sortOrderParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              10,
              0,
            );
            final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
            );
            final object = ConversationFolderEntity(
              internalId: internalIdParam,
              id: idParam,
              name: nameParam,
              sortOrder: sortOrderParam,
              createdAt: createdAtParam,
            );

            return object;
          },
        ),
    SavedMessageEntity: obx_int.EntityDefinition<SavedMessageEntity>(
      model: _entities[5],
      toOneRelations: (SavedMessageEntity object) => [],
      toManyRelations: (SavedMessageEntity object) => {},
      getId: (SavedMessageEntity object) => object.internalId,
      setId: (SavedMessageEntity object, int id) {
        object.internalId = id;
      },
      objectToFB: (SavedMessageEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final sourceMessageIdOffset = fbb.writeString(object.sourceMessageId);
        final conversationIdOffset = fbb.writeString(object.conversationId);
        final conversationTitleOffset = fbb.writeString(
          object.conversationTitle,
        );
        final contentOffset = fbb.writeString(object.content);
        final modelIdOffset = object.modelId == null
            ? null
            : fbb.writeString(object.modelId!);
        final folderIdOffset = object.folderId == null
            ? null
            : fbb.writeString(object.folderId!);
        fbb.startTable(12);
        fbb.addInt64(0, object.internalId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, sourceMessageIdOffset);
        fbb.addOffset(3, conversationIdOffset);
        fbb.addOffset(4, conversationTitleOffset);
        fbb.addInt32(5, object.roleIndex);
        fbb.addOffset(6, contentOffset);
        fbb.addOffset(7, modelIdOffset);
        fbb.addOffset(8, folderIdOffset);
        fbb.addInt64(9, object.savedAt.millisecondsSinceEpoch);
        fbb.addBool(10, object.isArchived);
        fbb.finish(fbb.endTable());
        return object.internalId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final internalIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sourceMessageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final conversationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final conversationTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final roleIndexParam = const fb.Int32Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final modelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final folderIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final savedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final object = SavedMessageEntity(
          internalId: internalIdParam,
          id: idParam,
          sourceMessageId: sourceMessageIdParam,
          conversationId: conversationIdParam,
          conversationTitle: conversationTitleParam,
          roleIndex: roleIndexParam,
          content: contentParam,
          modelId: modelIdParam,
          folderId: folderIdParam,
          savedAt: savedAtParam,
          isArchived: isArchivedParam,
        );

        return object;
      },
    ),
    SavedMessageFolderEntity:
        obx_int.EntityDefinition<SavedMessageFolderEntity>(
          model: _entities[6],
          toOneRelations: (SavedMessageFolderEntity object) => [],
          toManyRelations: (SavedMessageFolderEntity object) => {},
          getId: (SavedMessageFolderEntity object) => object.internalId,
          setId: (SavedMessageFolderEntity object, int id) {
            object.internalId = id;
          },
          objectToFB: (SavedMessageFolderEntity object, fb.Builder fbb) {
            final idOffset = fbb.writeString(object.id);
            final nameOffset = fbb.writeString(object.name);
            fbb.startTable(6);
            fbb.addInt64(0, object.internalId);
            fbb.addOffset(1, idOffset);
            fbb.addOffset(2, nameOffset);
            fbb.addInt64(3, object.sortOrder);
            fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
            fbb.finish(fbb.endTable());
            return object.internalId;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final internalIdParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final idParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final nameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final sortOrderParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              10,
              0,
            );
            final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
            );
            final object = SavedMessageFolderEntity(
              internalId: internalIdParam,
              id: idParam,
              name: nameParam,
              sortOrder: sortOrderParam,
              createdAt: createdAtParam,
            );

            return object;
          },
        ),
    ForkAnchorEntity: obx_int.EntityDefinition<ForkAnchorEntity>(
      model: _entities[7],
      toOneRelations: (ForkAnchorEntity object) => [],
      toManyRelations: (ForkAnchorEntity object) => {},
      getId: (ForkAnchorEntity object) => object.internalId,
      setId: (ForkAnchorEntity object, int id) {
        object.internalId = id;
      },
      objectToFB: (ForkAnchorEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final mainConversationIdOffset = fbb.writeString(
          object.mainConversationId,
        );
        final anchorMessageIdOffset = fbb.writeString(object.anchorMessageId);
        final selectedTextOffset = fbb.writeString(object.selectedText);
        final forkConversationIdOffset = fbb.writeString(
          object.forkConversationId,
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.internalId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, mainConversationIdOffset);
        fbb.addOffset(3, anchorMessageIdOffset);
        fbb.addOffset(4, selectedTextOffset);
        fbb.addOffset(5, forkConversationIdOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.internalId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final internalIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final mainConversationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final anchorMessageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final selectedTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final forkConversationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = ForkAnchorEntity(
          internalId: internalIdParam,
          id: idParam,
          mainConversationId: mainConversationIdParam,
          anchorMessageId: anchorMessageIdParam,
          selectedText: selectedTextParam,
          forkConversationId: forkConversationIdParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ConversationEntity] entity fields to define ObjectBox queries.
class ConversationEntity_ {
  /// See [ConversationEntity.internalId].
  static final internalId = obx.QueryIntegerProperty<ConversationEntity>(
    _entities[0].properties[0],
  );

  /// See [ConversationEntity.id].
  static final id = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[1],
  );

  /// See [ConversationEntity.title].
  static final title = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[2],
  );

  /// See [ConversationEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ConversationEntity>(
    _entities[0].properties[3],
  );

  /// See [ConversationEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ConversationEntity>(
    _entities[0].properties[4],
  );

  /// See [ConversationEntity.isPinned].
  static final isPinned = obx.QueryBooleanProperty<ConversationEntity>(
    _entities[0].properties[5],
  );

  /// See [ConversationEntity.personaId].
  static final personaId = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[6],
  );

  /// See [ConversationEntity.serverId].
  static final serverId = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[7],
  );

  /// See [ConversationEntity.modelId].
  static final modelId = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[8],
  );

  /// See [ConversationEntity.messageCount].
  static final messageCount = obx.QueryIntegerProperty<ConversationEntity>(
    _entities[0].properties[9],
  );

  /// See [ConversationEntity.lastMessagePreview].
  static final lastMessagePreview = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[10],
  );

  /// See [ConversationEntity.systemPrompt].
  static final systemPrompt = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[11],
  );

  /// See [ConversationEntity.temperature].
  static final temperature = obx.QueryDoubleProperty<ConversationEntity>(
    _entities[0].properties[12],
  );

  /// See [ConversationEntity.topP].
  static final topP = obx.QueryDoubleProperty<ConversationEntity>(
    _entities[0].properties[13],
  );

  /// See [ConversationEntity.maxTokens].
  static final maxTokens = obx.QueryIntegerProperty<ConversationEntity>(
    _entities[0].properties[14],
  );

  /// See [ConversationEntity.contextLength].
  static final contextLength = obx.QueryIntegerProperty<ConversationEntity>(
    _entities[0].properties[15],
  );

  /// See [ConversationEntity.mcpEnabled].
  static final mcpEnabled = obx.QueryBooleanProperty<ConversationEntity>(
    _entities[0].properties[16],
  );

  /// See [ConversationEntity.smartRepliesJson].
  static final smartRepliesJson = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[17],
  );

  /// See [ConversationEntity.smartRepliesLastMessageId].
  static final smartRepliesLastMessageId =
      obx.QueryStringProperty<ConversationEntity>(_entities[0].properties[18]);

  /// See [ConversationEntity.folderId].
  static final folderId = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[19],
  );

  /// See [ConversationEntity.isTemporary].
  static final isTemporary = obx.QueryBooleanProperty<ConversationEntity>(
    _entities[0].properties[20],
  );

  /// See [ConversationEntity.isArchived].
  static final isArchived = obx.QueryBooleanProperty<ConversationEntity>(
    _entities[0].properties[21],
  );

  /// See [ConversationEntity.characterCount].
  static final characterCount = obx.QueryIntegerProperty<ConversationEntity>(
    _entities[0].properties[22],
  );

  /// See [ConversationEntity.totalTokenCount].
  static final totalTokenCount = obx.QueryIntegerProperty<ConversationEntity>(
    _entities[0].properties[23],
  );

  /// See [ConversationEntity.forkOfMessageId].
  static final forkOfMessageId = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[24],
  );

  /// See [ConversationEntity.forkSpan].
  static final forkSpan = obx.QueryStringProperty<ConversationEntity>(
    _entities[0].properties[25],
  );

  /// See [ConversationEntity.isFork].
  static final isFork = obx.QueryBooleanProperty<ConversationEntity>(
    _entities[0].properties[26],
  );

  /// see [ConversationEntity.messages]
  static final messages =
      obx.QueryBacklinkToMany<MessageEntity, ConversationEntity>(
        MessageEntity_.conversation,
      );
}

/// [MessageEntity] entity fields to define ObjectBox queries.
class MessageEntity_ {
  /// See [MessageEntity.internalId].
  static final internalId = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[0],
  );

  /// See [MessageEntity.id].
  static final id = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[1],
  );

  /// See [MessageEntity.conversation].
  static final conversation =
      obx.QueryRelationToOne<MessageEntity, ConversationEntity>(
        _entities[1].properties[2],
      );

  /// See [MessageEntity.conversationUid].
  static final conversationUid = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[3],
  );

  /// See [MessageEntity.roleIndex].
  static final roleIndex = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[4],
  );

  /// See [MessageEntity.content].
  static final content = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[5],
  );

  /// See [MessageEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<MessageEntity>(
    _entities[1].properties[6],
  );

  /// See [MessageEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[7],
  );

  /// See [MessageEntity.modelId].
  static final modelId = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[8],
  );

  /// See [MessageEntity.tokenCount].
  static final tokenCount = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[9],
  );

  /// See [MessageEntity.errorMessage].
  static final errorMessage = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[10],
  );

  /// See [MessageEntity.attachmentPathsJson].
  static final attachmentPathsJson = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[11],
  );

  /// See [MessageEntity.generationTimeMs].
  static final generationTimeMs = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[12],
  );

  /// See [MessageEntity.reasoningContent].
  static final reasoningContent = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[13],
  );

  /// See [MessageEntity.toolCallsJson].
  static final toolCallsJson = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[14],
  );

  /// See [MessageEntity.toolCallId].
  static final toolCallId = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[15],
  );

  /// See [MessageEntity.isProcessing].
  static final isProcessing = obx.QueryBooleanProperty<MessageEntity>(
    _entities[1].properties[16],
  );

  /// See [MessageEntity.toolSessionId].
  static final toolSessionId = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[17],
  );

  /// See [MessageEntity.toolEventsJson].
  static final toolEventsJson = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[18],
  );

  /// See [MessageEntity.variantGroupId].
  static final variantGroupId = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[19],
  );

  /// See [MessageEntity.variantIndex].
  static final variantIndex = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[20],
  );

  /// See [MessageEntity.threadOrder].
  static final threadOrder = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[21],
  );

  /// See [MessageEntity.isActiveVariant].
  static final isActiveVariant = obx.QueryBooleanProperty<MessageEntity>(
    _entities[1].properties[22],
  );

  /// See [MessageEntity.parentMessageId].
  static final parentMessageId = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[23],
  );

  /// See [MessageEntity.inputTokenCount].
  static final inputTokenCount = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[24],
  );

  /// See [MessageEntity.tokensPerSecond].
  static final tokensPerSecond = obx.QueryDoubleProperty<MessageEntity>(
    _entities[1].properties[25],
  );

  /// See [MessageEntity.ttftMs].
  static final ttftMs = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[26],
  );

  /// See [MessageEntity.stopReason].
  static final stopReason = obx.QueryStringProperty<MessageEntity>(
    _entities[1].properties[27],
  );

  /// See [MessageEntity.contentTokenCount].
  static final contentTokenCount = obx.QueryIntegerProperty<MessageEntity>(
    _entities[1].properties[28],
  );
}

/// [PersonaEntity] entity fields to define ObjectBox queries.
class PersonaEntity_ {
  /// See [PersonaEntity.internalId].
  static final internalId = obx.QueryIntegerProperty<PersonaEntity>(
    _entities[2].properties[0],
  );

  /// See [PersonaEntity.id].
  static final id = obx.QueryStringProperty<PersonaEntity>(
    _entities[2].properties[1],
  );

  /// See [PersonaEntity.name].
  static final name = obx.QueryStringProperty<PersonaEntity>(
    _entities[2].properties[2],
  );

  /// See [PersonaEntity.emoji].
  static final emoji = obx.QueryStringProperty<PersonaEntity>(
    _entities[2].properties[3],
  );

  /// See [PersonaEntity.systemPrompt].
  static final systemPrompt = obx.QueryStringProperty<PersonaEntity>(
    _entities[2].properties[4],
  );

  /// See [PersonaEntity.description].
  static final description = obx.QueryStringProperty<PersonaEntity>(
    _entities[2].properties[5],
  );

  /// See [PersonaEntity.isBuiltIn].
  static final isBuiltIn = obx.QueryBooleanProperty<PersonaEntity>(
    _entities[2].properties[6],
  );

  /// See [PersonaEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<PersonaEntity>(
    _entities[2].properties[7],
  );

  /// See [PersonaEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<PersonaEntity>(
    _entities[2].properties[8],
  );

  /// See [PersonaEntity.category].
  static final category = obx.QueryStringProperty<PersonaEntity>(
    _entities[2].properties[9],
  );

  /// See [PersonaEntity.preferredParamsJson].
  static final preferredParamsJson = obx.QueryStringProperty<PersonaEntity>(
    _entities[2].properties[10],
  );
}

/// [ServerEntity] entity fields to define ObjectBox queries.
class ServerEntity_ {
  /// See [ServerEntity.internalId].
  static final internalId = obx.QueryIntegerProperty<ServerEntity>(
    _entities[3].properties[0],
  );

  /// See [ServerEntity.id].
  static final id = obx.QueryStringProperty<ServerEntity>(
    _entities[3].properties[1],
  );

  /// See [ServerEntity.name].
  static final name = obx.QueryStringProperty<ServerEntity>(
    _entities[3].properties[2],
  );

  /// See [ServerEntity.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<ServerEntity>(
    _entities[3].properties[3],
  );

  /// See [ServerEntity.host].
  static final host = obx.QueryStringProperty<ServerEntity>(
    _entities[3].properties[4],
  );

  /// See [ServerEntity.port].
  static final port = obx.QueryIntegerProperty<ServerEntity>(
    _entities[3].properties[5],
  );

  /// See [ServerEntity.apiKey].
  static final apiKey = obx.QueryStringProperty<ServerEntity>(
    _entities[3].properties[6],
  );

  /// See [ServerEntity.isDefault].
  static final isDefault = obx.QueryBooleanProperty<ServerEntity>(
    _entities[3].properties[7],
  );

  /// See [ServerEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ServerEntity>(
    _entities[3].properties[8],
  );

  /// See [ServerEntity.lastConnectedAt].
  static final lastConnectedAt = obx.QueryDateProperty<ServerEntity>(
    _entities[3].properties[9],
  );

  /// See [ServerEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<ServerEntity>(
    _entities[3].properties[10],
  );

  /// See [ServerEntity.iconName].
  static final iconName = obx.QueryStringProperty<ServerEntity>(
    _entities[3].properties[11],
  );

  /// See [ServerEntity.pathPrefix].
  static final pathPrefix = obx.QueryStringProperty<ServerEntity>(
    _entities[3].properties[12],
  );

  /// See [ServerEntity.availableRamGb].
  static final availableRamGb = obx.QueryIntegerProperty<ServerEntity>(
    _entities[3].properties[13],
  );

  /// See [ServerEntity.availableVramGb].
  static final availableVramGb = obx.QueryIntegerProperty<ServerEntity>(
    _entities[3].properties[14],
  );
}

/// [ConversationFolderEntity] entity fields to define ObjectBox queries.
class ConversationFolderEntity_ {
  /// See [ConversationFolderEntity.internalId].
  static final internalId = obx.QueryIntegerProperty<ConversationFolderEntity>(
    _entities[4].properties[0],
  );

  /// See [ConversationFolderEntity.id].
  static final id = obx.QueryStringProperty<ConversationFolderEntity>(
    _entities[4].properties[1],
  );

  /// See [ConversationFolderEntity.name].
  static final name = obx.QueryStringProperty<ConversationFolderEntity>(
    _entities[4].properties[2],
  );

  /// See [ConversationFolderEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<ConversationFolderEntity>(
    _entities[4].properties[3],
  );

  /// See [ConversationFolderEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ConversationFolderEntity>(
    _entities[4].properties[4],
  );
}

/// [SavedMessageEntity] entity fields to define ObjectBox queries.
class SavedMessageEntity_ {
  /// See [SavedMessageEntity.internalId].
  static final internalId = obx.QueryIntegerProperty<SavedMessageEntity>(
    _entities[5].properties[0],
  );

  /// See [SavedMessageEntity.id].
  static final id = obx.QueryStringProperty<SavedMessageEntity>(
    _entities[5].properties[1],
  );

  /// See [SavedMessageEntity.sourceMessageId].
  static final sourceMessageId = obx.QueryStringProperty<SavedMessageEntity>(
    _entities[5].properties[2],
  );

  /// See [SavedMessageEntity.conversationId].
  static final conversationId = obx.QueryStringProperty<SavedMessageEntity>(
    _entities[5].properties[3],
  );

  /// See [SavedMessageEntity.conversationTitle].
  static final conversationTitle = obx.QueryStringProperty<SavedMessageEntity>(
    _entities[5].properties[4],
  );

  /// See [SavedMessageEntity.roleIndex].
  static final roleIndex = obx.QueryIntegerProperty<SavedMessageEntity>(
    _entities[5].properties[5],
  );

  /// See [SavedMessageEntity.content].
  static final content = obx.QueryStringProperty<SavedMessageEntity>(
    _entities[5].properties[6],
  );

  /// See [SavedMessageEntity.modelId].
  static final modelId = obx.QueryStringProperty<SavedMessageEntity>(
    _entities[5].properties[7],
  );

  /// See [SavedMessageEntity.folderId].
  static final folderId = obx.QueryStringProperty<SavedMessageEntity>(
    _entities[5].properties[8],
  );

  /// See [SavedMessageEntity.savedAt].
  static final savedAt = obx.QueryDateProperty<SavedMessageEntity>(
    _entities[5].properties[9],
  );

  /// See [SavedMessageEntity.isArchived].
  static final isArchived = obx.QueryBooleanProperty<SavedMessageEntity>(
    _entities[5].properties[10],
  );
}

/// [SavedMessageFolderEntity] entity fields to define ObjectBox queries.
class SavedMessageFolderEntity_ {
  /// See [SavedMessageFolderEntity.internalId].
  static final internalId = obx.QueryIntegerProperty<SavedMessageFolderEntity>(
    _entities[6].properties[0],
  );

  /// See [SavedMessageFolderEntity.id].
  static final id = obx.QueryStringProperty<SavedMessageFolderEntity>(
    _entities[6].properties[1],
  );

  /// See [SavedMessageFolderEntity.name].
  static final name = obx.QueryStringProperty<SavedMessageFolderEntity>(
    _entities[6].properties[2],
  );

  /// See [SavedMessageFolderEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<SavedMessageFolderEntity>(
    _entities[6].properties[3],
  );

  /// See [SavedMessageFolderEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<SavedMessageFolderEntity>(
    _entities[6].properties[4],
  );
}

/// [ForkAnchorEntity] entity fields to define ObjectBox queries.
class ForkAnchorEntity_ {
  /// See [ForkAnchorEntity.internalId].
  static final internalId = obx.QueryIntegerProperty<ForkAnchorEntity>(
    _entities[7].properties[0],
  );

  /// See [ForkAnchorEntity.id].
  static final id = obx.QueryStringProperty<ForkAnchorEntity>(
    _entities[7].properties[1],
  );

  /// See [ForkAnchorEntity.mainConversationId].
  static final mainConversationId = obx.QueryStringProperty<ForkAnchorEntity>(
    _entities[7].properties[2],
  );

  /// See [ForkAnchorEntity.anchorMessageId].
  static final anchorMessageId = obx.QueryStringProperty<ForkAnchorEntity>(
    _entities[7].properties[3],
  );

  /// See [ForkAnchorEntity.selectedText].
  static final selectedText = obx.QueryStringProperty<ForkAnchorEntity>(
    _entities[7].properties[4],
  );

  /// See [ForkAnchorEntity.forkConversationId].
  static final forkConversationId = obx.QueryStringProperty<ForkAnchorEntity>(
    _entities[7].properties[5],
  );

  /// See [ForkAnchorEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ForkAnchorEntity>(
    _entities[7].properties[6],
  );
}
